opentrials/reviewapp/urls.py
from django.conf.urls.defaults import *
from django.contrib.auth.views import login, logout
from django.contrib.auth.views import password_reset, password_reset_done
from django.contrib.auth.views import password_reset_complete, password_reset_confirm
from django.views.generic.list_detail import object_list, object_detail

from reviewapp.views import index, user_dump, new_submission, submissions_list
from reviewapp.views import dashboard, submission_detail, user_profile
from reviewapp.views import upload_trial, open_remark, resend_activation_email
from reviewapp.views import change_remark_status
from reviewapp.views import contact

from reviewapp.models import Submission, News


submissions = {
   'queryset':Submission.objects.all()
}

news = {
    'queryset': News.objects.filter(status__exact='published').order_by('-created',),
}

urlpatterns = patterns('',

    url(r'^news/$', object_list, news, name='reviewapp.newslist'),
    
    url(r'^news/(?P<object_id>\d+)/$', object_detail, news, name='reviewapp.news'),

    url(r'^accounts/dashboard/$', dashboard, name='reviewapp.dashboard'),

    url(r'^accounts/profile/$', user_profile, name='reviewapp.userhome'),

    url(r'^accounts/uploadtrial/$', upload_trial, name='reviewapp.uploadtrial'), #same as accounts/profile

    url(r'^accounts/submissionlist/$', submissions_list, name='reviewapp.submissionlist'), #same as accounts/profile

    url(r'^accounts/submission/(\d+)/$', submission_detail, 
        name='reviewapp.submission'),

    url(r'^accounts/newsubmission/$', new_submission,
        name='reviewapp.new_submission'),

    url(r'^accounts/userdump/$', user_dump),

    url(r'^accounts/login/$', login, dict(template_name='reviewapp/login.html',redirect_field_name='/'),
        name='reviewapp.login'),

    url(r'^accounts/logout/$', logout, dict(next_page='/'),
        name='reviewapp.logout'),
        
    url(r'^accounts/resend/activation/email/$', resend_activation_email,
        name='reviewapp.resend_activation_email'),

    url(r'^accounts/password/reset/$', password_reset, {
        'template_name': 'reviewapp/password_reset_form.html',
        'email_template_name': 'reviewapp/password_reset_email.html',
        'post_reset_redirect': '/accounts/password/reset/done/'}, 
        name='reviewapp.password_reset'),

    url(r'^accounts/password/reset/done/$', password_reset_done, 
        {'template_name': 'reviewapp/password_reset_done.html'},
        name='reviewapp.password_reset_done'),
        
    url(r'^accounts/password/reset/(?P<uidb36>[0-9A-Za-z]+)-(?P<token>.+)/$', password_reset_confirm, {
        'template_name': 'reviewapp/password_reset_confirm.html',
        'post_reset_redirect': '/accounts/password/reset/complete/'},
        name='reviewapp.password_reset_confirm'),
        
    url(r'^accounts/password/reset/complete/$', password_reset_complete, 
        {'template_name': 'reviewapp/password_reset_complete.html'}, 
        name='reviewapp.password_reset_complete'),
        
    url(r'^remark/open/(?P<submission_id>\d+)/(?P<context>[a-zA-Z0-9_\- ]+)/$', open_remark,
        name='reviewapp.openremark'),
        
    url(r'^contact/$', contact, name='reviewapp.contact'),

    url(r'^remark/change/(?P<remark_id>\d+)/(?P<status>[a-z]+)/$', change_remark_status,
        name='reviewapp.changeremarkstatus'),

    url(r'^$', index, name='reviewapp.home'),  
)

opentrials/urls.py
from django.conf.urls.defaults import *

import utilities

from django.contrib import admin # Django admin UI
admin.autodiscover()             # Django admin UI

urlpatterns = patterns('',
    # Repository application
    url(r'^rg/', include('opentrials.repository.urls')),

    # Tickets application
    url(r'^ticket/', include('opentrials.tickets.urls')),

    # Assistance application
    url(r'^assistance/', include('opentrials.assistance.urls')),

    # Review application
    url(r'^', include('opentrials.reviewapp.urls')),

    # Django admin UI and documentation
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    url(r'^admin/', include(admin.site.urls)),

    url(r'^decs/', include('opentrials.decsclient.urls')),

    # django-registration views
    url(r'^accounts/', include('registration.backends.default.urls')),

    # system diagnostic views (may be disabled in production)
    url(r'^diag/', include('opentrials.diagnostic.urls')),


)

from django.conf import settings
if settings.DEBUG:
    # serve static files from develpment server
    from django.views import static
    urlpatterns += patterns('',
        url(r'^static/(?P<path>.*)$', 'django.views.static.serve',
            {'document_root': settings.MEDIA_ROOT}),
    )

if 'rosetta' in settings.INSTALLED_APPS:
    urlpatterns += patterns('',
        url(r'^rosetta/', include('rosetta.urls')),
    )

opentrials/reviewapp/models.py
import pickle
from datetime import datetime

from django.db import models
from django.db.models.signals import post_save
from django.contrib.auth.models import User
from django.utils.translation import ugettext_lazy as _

from repository.models import ClinicalTrial, Institution
from repository.choices import PROCESSING_STATUS, PUBLISHED_STATUS
from tickets.models import Ticket
from utilities import safe_truncate
from vocabulary.models import CountryCode

from consts import REMARK, MISSING, PARTIAL, COMPLETE
import settings


SUBMISSION_STATUS = [
    ('draft', 'draft'), # clinical trial is 'processing'
    ('pending', 'pending'), # clinical trial remains 'processing'
    ('approved', 'approved'), # clinical trial is 'published'
    ('rejected', 'rejected'), # clinical trial remains or becomes 'processing'
]
STATUS_DRAFT = SUBMISSION_STATUS[0][0]
STATUS_PENDING = SUBMISSION_STATUS[1][0]
STATUS_APPROVED = SUBMISSION_STATUS[2][0]
STATUS_REJECTED = SUBMISSION_STATUS[3][0]


ACCESS = [
    ('public', 'Public'),
    ('private', 'Private'),
]

class UserProfile(models.Model):
    user = models.ForeignKey(User, unique=True)
    preferred_language = models.CharField(_('Preferred language'),max_length=10,
                                choices=settings.MANAGED_LANGUAGES_CHOICES,
                                default=settings.MANAGED_LANGUAGES_CHOICES[-1][0])
                                
    def amount_submissions(self):
        return u"%03d" % (Submission.objects.filter(creator=self.user).count())

    def amount_tickets(self):
        return u"%03d" % (Ticket.objects.filter(creator=self.user).count())
       

class Submission(models.Model):
    class Meta:
        ordering = ['-created']
        permissions = (
            ("review", "Can review"),
        )

    creator = models.ForeignKey(User, related_name='submission_creator', editable=False)
    created = models.DateTimeField(default=datetime.now, editable=False)
    updater = models.ForeignKey(User, null=True, related_name='submission_updater', editable=False)
    updated = models.DateTimeField(null=True, editable=False)
    title = models.TextField(u'Scientific title', max_length=2000)
    primary_sponsor = models.OneToOneField(Institution, null=True, blank=True,
                                    verbose_name=_('Primary Sponsor'))

    trial = models.OneToOneField(ClinicalTrial, null=True)
    status = models.CharField(_('Status'), max_length=64,
                              choices=SUBMISSION_STATUS,
                              default=SUBMISSION_STATUS[0][0])
    fields_status = models.TextField(_('Fields Status'), max_length=512, null=True, 
                                     blank=True, editable=False)
    language = models.CharField(_('Submission language'), max_length=10,
                                choices=settings.MANAGED_LANGUAGES_CHOICES)
    staff_note = models.TextField(_('Submission note (staff use only)'), max_length=255,
                                    blank=True)

    def save(self):
        if self.id:
            self.updated = datetime.now()
        if self.status == STATUS_APPROVED and self.trial.status == PROCESSING_STATUS:
            self.trial.status = PUBLISHED_STATUS
            self.trial.save()
        if self.status == STATUS_REJECTED and self.trial.status == PUBLISHED_STATUS:
            self.trial.status = PROCESSING_STATUS
            self.trial.save()

        super(Submission, self).save()

    def short_title(self):
        return safe_truncate(self.title, 120)

    def creator_username(self):
        return self.creator.username

    def __unicode__(self):
        return self.short_title()

    def get_mandatory_languages(self):
        langs = set([u'en'])
        if self.trial.primary_sponsor is not None:
            langs.add(self.trial.primary_sponsor.country.submission_language)

        for rc in self.trial.recruitment_country.all():
            langs.add(rc.submission_language)

        return langs.intersection(set(settings.MANAGED_LANGUAGES))

    def get_trans_languages(self):
        return self.get_mandatory_languages() - set([self.language])

    def get_secondary_language(self):
        sec = None
        for lang in self.get_mandatory_languages():
            # fixme: get from settings
            if lang != 'en':
                sec = lang.lower()
                break
        return sec

    def get_absolute_url(self):
        # TODO: use reverse to replace absolute path
        return '/accounts/submission/%s/' % self.id

    def get_fields_status(self):
        if not getattr(self, '_fields_status', None):
            self._fields_status = pickle.loads(self.fields_status.encode('utf-8'))

        return self._fields_status

    def get_status(self):
        status = [field for step in self.get_fields_status().values() for field in step.values()]
        if REMARK in status:
            return REMARK
        elif MISSING in status:
            return MISSING
        elif PARTIAL in status:
            return PARTIAL
        return COMPLETE

class RecruitmentCountry(models.Model):
    class Meta:
        verbose_name_plural = _('Recruitment Countries')

    submission = models.ForeignKey(Submission)
    country = models.ForeignKey(CountryCode, verbose_name=_('Country'), related_name='submissionrecruitmentcountry_set')

class Attachment(models.Model):
    class Meta:
        verbose_name_plural = _('Attachments')
    file = models.FileField(_('File'), upload_to=settings.ATTACHMENTS_PATH)
    description = models.TextField(_('Description'),blank=True,max_length=8000)
    submission = models.ForeignKey(Submission)
    public = models.BooleanField(_('Public'))

    def get_relative_url(self):
        return self.file.url.replace(settings.PROJECT_PATH, u'')

REMARK_STATUS = [
    # initial state, as created by reviewer
    ('opened', _('Opened')),
    # marked as noted by user
    ('acknowledged', _('Acknowledged')),
    # final state, after reviewer verifies changes by the user
    ('closed', _('Closed')),
]

REMARK_TRANSITIONS = {
    'opened':['acknowledged'],
    'acknowledged':['closed','opened'],
    'closed':[],
}

class RemarksOpened(models.Manager):
    def get_query_set(self):
        return super(RemarksOpened, self).get_query_set().filter(status__exact='opened')

class RemarksAcknowledged(models.Manager):
    def get_query_set(self):
        return super(RemarksAcknowledged, self).get_query_set().filter(status__exact='acknowledged')

class RemarksClosed(models.Manager):
    def get_query_set(self):
        return super(RemarksClosed, self).get_query_set().filter(status__exact='closed')

class Remark(models.Model):
    ''' A reviewer comment regarding a submission field.

    The remark is directed at the field identified by the context attribute.
    '''
    creator = models.ForeignKey(User, editable=False)
    created = models.DateTimeField(default=datetime.now, editable=False)
    submission = models.ForeignKey(Submission)
    context = models.CharField(_('Context'), max_length=256, blank=True)
    text = models.TextField(_('Text'), max_length=2048)
    status = models.CharField(_('Status'), max_length=16, choices=REMARK_STATUS,
                              default=REMARK_STATUS[0][0])

    objects = models.Manager()
    opened = RemarksOpened()
    acknowledged = RemarksAcknowledged()
    closed = RemarksClosed()

    def __unicode__(self):
        return '%s:%s' % (self.pk, self.submission_id)

    def short_text(self):
        return safe_truncate(self.text, 60)

NEWS_STATUS = [
    ('pending', _('Pending')),
    ('published', _('Published')),
]

class News(models.Model):

    class Meta:
        verbose_name_plural = _('News')

    title = models.CharField(_('Title'), max_length=256)
    text = models.TextField(_('Text'), max_length=2048)
    created = models.DateTimeField(default=datetime.now, editable=False)
    creator = models.ForeignKey(User, related_name='news_creator', editable=False)
    status = models.CharField(_('Status'), max_length=16, choices=NEWS_STATUS,
                              default=NEWS_STATUS[0][0])

    def short_title(self):
        return safe_truncate(self.title, 120)
        
    def short_text(self):
        return safe_truncate(self.text, 240)
    
    def __unicode__(self):
        return '%s' % (self.short_title())

# SIGNALS
def create_user_profile(sender, instance,**kwargs):
    UserProfile.objects.get_or_create(user=instance)
    
post_save.connect(create_user_profile, sender=User)

opentrials/reviewapp/forms.py
# coding: utf-8

from opentrials.repository.trds_forms import ReviewModelForm
from opentrials.reviewapp.models import Remark
from opentrials.reviewapp.models import UserProfile
from opentrials.reviewapp.models import Attachment, Submission
from django import forms
from django.utils.translation import ugettext as _
from django.contrib.auth.models import User
from django.conf import settings

from repository.models import Institution, CountryCode

ACCESS = [
    ('public', 'Public'),
    ('private', 'Private'),
]


class InitialTrialForm(ReviewModelForm):
    class Meta:
        model = Submission
        exclude = ['primary_sponsor', 'trial', 'status', 'staff_note', 'title']
        
    def __init__(self, *args, **kwargs):
        self.user = kwargs.pop('user', None)
        super(InitialTrialForm, self).__init__(*args, **kwargs)
        if self.user:
            self.fields['language'] = forms.ChoiceField(label=_('Submission language'), 
                        choices=settings.MANAGED_LANGUAGES_CHOICES, 
                        initial=self.user.get_profile().preferred_language)
            
    form_title = _('Initial Trial Data')
    scientific_title = forms.CharField(widget=forms.Textarea, 
                                       label=_('Scientific Title'), 
                                       max_length=2000)
    recruitment_country = forms.MultipleChoiceField(
                                label=_('Recruitment country'), 
                                choices=((cc.pk,cc.description) for cc in CountryCode.objects.iterator()))
    language = forms.ChoiceField(label=_('Submission language'), 
                                 choices=settings.MANAGED_LANGUAGES_CHOICES)
    
class PrimarySponsorForm(ReviewModelForm):
    class Meta:
        model = Institution
        exclude = ['address']
    form_title = _('Primary Sponsor')

class ExistingAttachmentForm(forms.ModelForm):
    class Meta:
        model = Attachment
        exclude = ['submission']

    title = _('Existing Attachment')
    file = forms.CharField(required=False,label=_('File'),max_length=255)

class NewAttachmentForm(ReviewModelForm):
    class Meta:
        model = Attachment
        fields = ['file','description','public']

    title = _('New Attachment')
    
class UserForm(forms.ModelForm):
    def clean_email(self):
        """
        Validate that the supplied email address is unique for the
        site.
        
        """
        if self.cleaned_data['email'] != self.instance.email:
            if User.objects.filter(email__iexact=self.cleaned_data['email']):
                raise forms.ValidationError(_("This email address is already in use. Please supply a different email address."))
        return self.cleaned_data['email']
        
    class Meta:
        model = User
        fields = ['first_name','last_name','email']
    
    title = _('User Profile')

class UserProfileForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ['preferred_language']

    title = _('Aditional info for profile')

class UploadTrial(forms.Form):
    submission_xml = forms.CharField(widget=forms.FileInput,required=True)

class OpenRemarkForm(forms.ModelForm):
    class Meta:
        model = Remark
        exclude = ['submission','context','status']

    title = _('Open Remark')
    
class ContactForm(forms.Form):
    name = forms.CharField(label=_("Name"), max_length=50)
    from_email = forms.EmailField(label=_("E-mail"))
    subject = forms.CharField(label=_("Subject"), max_length=50)
    message = forms.CharField(label=_("Message"), widget=forms.Textarea)

opentrials/reviewapp/templates/reviewapp/contact.html
{% extends "base_columns.html" %}

{% load i18n %}

{% block body_title %}{% trans 'Contact us' %}{% endblock %}

{% block stepmenu_top %}
    {{ block.super }}
    <big>/ {% trans 'Contact us' %}</big>
{% endblock %}

{% block body %}

    {% if form.errors %}
    <div class="warning"><strong>{% trans 'Please fill out all fields correctly.' %}</strong></div>
    {% endif %}

    {% if sent %}
    <div class="success"><strong>{% trans 'Message sent successfully.' %}</strong></div>
    {% endif %}

    <form method="post" action="./">{% csrf_token %}
    <fieldset>
        <legend>{% trans 'Fill out the fields below to enter contact us' %}</legend>

        <table class="dataTable" cellspacing="0">
        {{ form.as_table }}
        </table>
        <button type="submit" title="{% trans 'Send message' %}">{% trans 'Send' %}</button>
    </fieldset>
    </form>

{% endblock %}

opentrials/reviewapp/templates/reviewapp/dashboard.html
{% extends "base.html" %}
{% load i18n %}

{% block stepmenu_top %}
    {{ block.super }}
    <big>/ {% trans 'Dashboard' %}</big>
{% endblock %}

{% block body %}

<div class="leftCol">
    <div class="submissions">
        <h2>{% trans "Submissions" %}</h2>
        <div class="actions"><a href="{% url reviewapp.new_submission %}" class="button addNew">{% trans 'New Submission' %}</a></div>
        <table class="dataTable" cellpadding="0" cellspacing="0" border="0">
            <thead>
                <tr>
                    <th>{% trans 'Date' %}</th>
                    <th>{% trans 'Title' %}</th>
                    <th>{% trans 'Status' %}</th>
                </tr>
            </thead>
            <tbody>
                {% for submission in user_submissions %}
                <tr class="{% cycle 'even' 'odd' %}">
                    <td class="date">{{ submission.created|date:'Y/m/d H:i' }}</td>
                    <td class="title">
                        <a href="{% url repository.edittrial submission.trial.pk %}">{{ submission.short_title }}</a>
                    </td>
                    <td>{{ submission.status }}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
        <a href="{% url reviewapp.submissionlist %}" class="button showAll">{% trans 'Show all' %}</a>
    </div>
</div>
<div class="rightCol">
    <div class="tickets">
        <h2>{% trans 'Remarks' %}</h2>
        <table class="dataTable" cellpadding="0" cellspacing="0" border="0">
            <tr>
                <th>{% trans "Date" %}</th>
                <th>{% trans "Submission" %}</th>
                <th>{% trans "Context" %}</th>
                <th>{% trans "Text" %}</th>
            </tr>
            {% for remark in remarks %}
            <tr class="{% cycle 'even' 'odd' %}">
                <td class="date">{{ remark.created|date:'Y/m/d H:i' }}</td>
                <td class="subject">{{ remark.submission|truncatewords:6 }}</td>
                <td>{{ remark.context }}</td>
                <td>{{ remark.short_text }}</td>
            </tr>
            {% endfor %}
        </table>
        <a href="{% url ticket.index %}" class="button showAll">{% trans 'Show all' %}</a>
    </div>
</div>
<div class="spacer">
    &#160;
</div>

{% endblock %}

opentrials/reviewapp/templates/reviewapp/index.html
{% extends "base_columns.html" %}

{% load i18n %}

{% block body %}
    <div class="news">
    
    {% if page %}
        <a class="NewsExcerpt" href="/about/" title="{% trans 'Read more' %}">{{ page.content|safe }}</a>
    {% endif %}
    
    <table border="0" cellpading="0" cellspacing="0">
    <tr>
        <td>
            <h2><a title="{% trans 'List all' %}" href="{% url repository.index %}">{% trans 'Registered trials' %}</a></h2>
        </td>
        <td>
            <div class="highlights">
                <ul>
                    <li><a href="{% url reviewapp.new_submission %}" title="{% trans 'New Submission' %}"><img src="/static/images/button_newSubmission.jpg" alt="{% trans 'New Submission' %}"/></a></li>
                </ul>
            </div>
        </td>
    </tr>
    </table>

    {% if clinical_trials %}
        <ul>
        {% for ct in clinical_trials %}
            <li>
                <a class="NewsTitle" href="{% url repository.trial_registered ct.trial_id %}">{{ ct.main_title }}</a>
                <p>
                    <b>{% trans 'Primary Id Number' %}</b>: <a class="pnumber" href="{% url repository.trial_registered ct.trial_id %}">{{ ct.trial_id }}</a><br/>
                </p>
            </li>
        {% endfor %}
        </ul>
    {% else %}
        <p>{% trans 'No clinical trials have been published.' %}</p>
    {% endif %}
    </div>
{% endblock %}

opentrials/reviewapp/templates/reviewapp/login.html
{% extends "base_columns.html" %}

{% load i18n %}

{% block login %}{% endblock %}

{% block stepmenu_top %}
    {{ block.super }}
    <big>/ {% trans 'Login' %}</big>
{% endblock %}

{% block body %}

{% if form.errors %}
    <p>{% trans "Your username and password didn't match. Please try again." %}</p>
{% endif %}

<form method="post" action="{% url django.contrib.auth.views.login %}">{% csrf_token %}
    <table>
        <tr>
            <td>{{ form.username.label_tag }}</td>
            <td>{{ form.username }}</td>
        </tr>
        <tr>
            <td>{{ form.password.label_tag }}</td>
            <td>{{ form.password }}</td>
        </tr>
    </table>
    <input type="submit" value="login" />
    <input type="hidden" name="next" value="" />
</form>
<a href="/accounts/register" title="{% trans 'create an account to submit trial records' %}">
    {% trans 'Register' %}</a>
<a href="{% url reviewapp.password_reset %}" title="{% trans 'Forgot password?' %}">
    {% trans 'Forgot password?' %}</a>

{% endblock %}

opentrials/reviewapp/templates/reviewapp/new_submission.html
{% extends "base.html" %}
{% load i18n %}

{% block extrahead %}
        <script type="text/javascript">
            $(document).ready(function() {
                $("select[multiple]").asmSelect({
                        addItemTarget: 'bottom',
                        animate: true,
                        highlight: true,
                        sortable: false
                });
                $('.dataTable th img').cluetip({sticky: true, closePosition: 'title',local:true, cursor: 'pointer'});
            });
        </script>
{% endblock %}

{% block stepmenu_top %}
    {{ block.super }}
    <small>
        / <a href="{% url reviewapp.submissionlist %}">{% trans 'Submissions' %}</a>
    </small>
    <big>/ {% trans 'New Submission' %}</big>
{% endblock %}

{% block body %}

<form method="post" action="/accounts/newsubmission/" enctype="multipart/form-data">{% csrf_token %}
{% for form in forms %}
<fieldset>
    <legend>{{ form.form_title }}</legend>
    <table id="table_{{ forloop.counter }}" class="dataTable" cellspacing="0">
        {{ form.as_table }}
    </table>
</fieldset>
{% endfor %}

<input name="submit" type="submit" value="{% trans "Submit" %}"/>
</form>

{% endblock %}

opentrials/reviewapp/templates/reviewapp/news_detail.html
{% extends "base_columns.html" %}

{% load i18n %}

{% block body_title %}{% trans 'News' %}{% endblock %}

{% block stepmenu_top %}
    {{ block.super }}
    <small>
        / <a href="{% url reviewapp.newslist %}">{% trans 'News' %}</a>
    </small>
    <big>/ {{ object.title|truncatewords:5 }}</big>
{% endblock %}

{% block body %}

{% if object %}

    <span class="NewsTitle">{{ object.title }}</span>

    <p>{{ object.text|linebreaks }}</p>
    <br />

    <div class="date">{% trans 'Created:' %} {{ object.created|date:'d/m/Y - H:i' }}</div>
    
{% else %}
    <p>{% trans 'News unavailable.' %}</p>
{% endif %}
{% endblock %}

opentrials/reviewapp/templates/reviewapp/news_list.html
{% extends "base_columns.html" %}

{% load i18n %}

{% block body_title %}{% trans 'News' %}{% endblock %}

{% block stepmenu_top %}
    {{ block.super }}
    <big>/ {% trans 'News' %}</big>
{% endblock %}

{% block body %}

<div class="news">

    {% if object_list %}
        <ul>
        {% for object in object_list %}
            <li>
                <small>{{ object.created|date:'d/m/Y - H:i' }}</small> 
                <a class="NewsTitle" title="{{ object.title }}" href="{% url reviewapp.news object.id %}">{{ object.title }}</a>
                <a class="NewsExcerpt" href="{% url reviewapp.news object.id %}">{{ object.short_text }}</a>
            </li>
        {% endfor %}
        </ul>
    {% else %}
        <p>{% trans 'No news have been published.' %}</p>
    {% endif %}
</div>
{% endblock %}

opentrials/reviewapp/templates/reviewapp/password_reset_complete.html
{% extends "base_columns.html" %}

{% load i18n %}

{% block stepmenu_top %}
    {{ block.super }}
    <big>/ {% trans 'Reset password complete' %}</big>
{% endblock %}

{% block body %}
<p>
{% trans "Your password has been reset! You may now" %} 
<a href="{% url reviewapp.login %}"> {% trans "log in" %}</a>.
</p>
{% endblock %}

opentrials/reviewapp/templates/reviewapp/password_reset_confirm.html
{% extends "base_columns.html" %}

{% load i18n %}

{% block stepmenu_top %}
    {{ block.super }}
    <big>/ {% trans 'Reset password' %}</big>
{% endblock %}

{% block body %}
<p>
{% trans "Enter your new password below to reset your password:" %}
</p>
<form method="post" action="">{% csrf_token %}
<table>
    {{ form.as_table }}
    <tr><td></td><td><input type="submit" value="Set password" /></td></tr>
</table>
</form>
{% endblock %}

opentrials/reviewapp/templates/reviewapp/password_reset_done.html
{% extends "base_columns.html" %}

{% load i18n %}

{% block stepmenu_top %}
    {{ block.super }}
    <small>
        / <a href="{% url reviewapp.password_reset %}">{% trans 'Forgot Password?' %}</a>
    </small>
    <big>/ {% trans 'E-mail sent' %}</big>
{% endblock %}

{% block body %}
<p>
{% trans "We have sent you an email with a link to reset your password. Please check your email and click the link to continue." %}
</p>
{% endblock %}

opentrials/reviewapp/templates/reviewapp/password_reset_form.html
{% extends "base_columns.html" %}
{% load i18n %}

{% block stepmenu_top %}
    {{ block.super }}
    <big>/ {% trans 'Forgot password?' %}</big>
{% endblock %}

{% block body %}

<p>
{% trans "Enter your email in the form below and we'll send you instructions for creating a new one." %}
</p>
<form method="post" action="">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Reset password" />
</form>
<script type="text/javascript">
  var email = document.location.href.match(/\?email=([^&]*)/);
  if( email ){$("#id_email").val(email[1]);}
</script>
{% endblock %}

opentrials/reviewapp/templates/reviewapp/user_profile.html
{% extends "base.html" %}
{% load i18n %}

{% block extrahead %}
<style type="text/css">
#id_email  {
    width:300px;
}
#id_preferred_language  {
    width:190px;
}
</style>
{% endblock %}

{% block stepmenu_top %}
    {{ block.super }}
    <big>/ {% trans 'Profile' %}</big>
{% endblock %}

{% block body %}

<form action="./" method="post">{% csrf_token %}
    <fieldset>
        <legend>{% trans "Change your profile" %}</legend>
        <table class="table">
            <col width="20%"/>
            <col width="80%"/>
            {{ user_form.as_table }}
            {{ profile_form.as_table }}
        </table>
    </fieldset>
    
    <fieldset>
        <legend>{% trans "Change your password" %}</legend>
        <table class="table">
            <col width="20%"/>
            <col width="80%"/>
            {{ password_form.as_table }}
        </table>
    </fieldset>
    <input type="submit" value="{% trans 'Save' %}"/>
</form>
{% endblock %}